version: '3.8'

services:
    nginx:
        restart: always
        build:
            dockerfile: dockerfile
            context: ./nginx
        ports:
            - ${nginx_port1}:${nginx_port2}
        env_file: 
            - .env
        volumes: 
            - myapp_socket:/tmp/myapp_socket:ro     # docker volumes
        depends_on: 
            - server_myapp

    server_myapp:
        restart: always
        build:
            dockerfile: dockerfile
            context: ./myapp
        env_file: 
            - .env
        volumes: 
            - ./myapp/server:/app/server
            - /app/server/.env      # exclude
            - ./myapp/client/dist:/app/client/dist
            - myapp_socket:/tmp/myapp_socket        # docker volumes
        links:
            - db:myapp
        depends_on: 
            - db

    
    # server_blog:

    # server_privateserver:

    db:
        restart: always
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '${mysql_password}'
        ports: 
            - ${db_port1}:${db_port2}

volumes:
    myapp_socket: