version: "3.3"

services:
  jenkins:
    container_name: jenkins
    restart: always
    build:
      dockerfile: dockerfile
      context: ./jenkins
    ports:
      - 8282:8080
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "Asia/Seoul"
