version: "3.3"

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      dockerfile: ./nginx/dockerfile
      context: ./
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - myapp_socket:/tmp/myapp_socket:ro
    depends_on:
      - server_myapp

  server_myapp:
    container_name: myapp
    restart: always
    build:
      dockerfile: ./server/dockerfile
      context: ./myapp
    env_file:
      - .env
    volumes:
      - myapp_socket:/tmp/myapp_socket
    links:
      - mysql:myapp_mysql
      - redis:myapp_redis
    depends_on:
      - mysql
      - redis

  redis:
    container_name: redis
    restart: always
    image: redis:alpine

  mysql:
    container_name: mysql
    restart: always
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${mysql_password}"
      MYSQL_MYAPP_PASSWORD: "${myapp_password}"
    ports:
      - ${mysql_port1}:${mysql_port2}
    volumes:
      - ./shell/mysql/:/shell/
    cap_add:
      - SYS_NICE

volumes:
  myapp_socket:
