FROM nginx:1.20-alpine
# sh

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/index /etc/nginx/index
COPY ./shell/nginx /shell

RUN apk update && apk upgrade
RUN apk add --no-cache certbot certbot-nginx

#certbot renew —dry-run
#certbot certificates