FROM python:3.7-alpine
# sh

RUN apk update && apk upgrade
RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev python3-dev make libevent-dev build-base

COPY ./server/requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY ./server /app/server
COPY ./client/dist /app/client/dist

# RUN apk del gcc musl-dev libffi-dev openssl-dev python3-dev make libevent-dev build-base

WORKDIR /app/server
RUN mkdir -p /tmp/myapp_socket/
CMD ["gunicorn", "-k", "gevent","--workers", "1", \
    "--worker-connections", "100", "--max-requests", "0", \
    "--bind", "unix:/tmp/myapp_socket/myapp.sock", \
    "wsgi:app", \
    "--worker-tmp-dir", "/tmp/myapp_socket/", \
    "--reload"]